import{auth,db,firebaseReady}from'./firebase-config.js';
import{signInWithEmailAndPassword,onAuthStateChanged,signOut}from'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import{addDoc,collection,deleteDoc,doc,getDocs,orderBy,query,setDoc}from'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const $=s=>document.querySelector(s);let skills=[];const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
async function load(){let x=await getDocs(query(collection(db,'skills'),orderBy('order')));skills=x.docs.map(d=>({id:d.id,...d.data()}));$('#list').innerHTML=skills.length?skills.map(s=>`<div class="skill-row"><div><strong>${esc(s.name)}</strong><span>${esc(s.category)}</span></div><div><button class="quiet" data-e="${s.id}">Edit</button> <button class="delete" data-d="${s.id}">Delete</button></div></div>`).join(''):'<p>No skills added yet.</p>'}
function showPreview(url){const preview=$('#logoPreview');preview.src=url||'';preview.hidden=!url}
function reset(){$('#form').reset();$('#id').value='';showPreview('');$('#save').textContent='Publish skill';$('#cancel').hidden=true;$('#note').textContent='Fill this in and publish it instantly.'}
$('#logoUrl').oninput=()=>showPreview($('#logoUrl').value.trim());
if(!firebaseReady)$('#login').innerHTML='<h2>Firebase needs setup</h2><p>Add your Firebase configuration in firebase-config.js, then reload this page.</p>';else{onAuthStateChanged(auth,async u=>{$('#login').hidden=!!u;$('#dash').hidden=!u;if(u)await load()});$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('#email').value,$('#password').value)}catch{alert('Could not sign in. Check your email and password.')}};$('#out').onclick=()=>signOut(auth);$('#form').onsubmit=async e=>{e.preventDefault();const button=$('#save');button.disabled=true;button.textContent='Saving…';try{let id=$('#id').value,data={name:$('#name').value.trim(),category:$('#category').value.trim().toUpperCase(),icon:$('#icon').value.trim()||'+',logoUrl:$('#logoUrl').value.trim(),color:$('#color').value,description:$('#description').value.trim(),order:id?skills.find(s=>s.id===id).order:Date.now()};id?await setDoc(doc(db,'skills',id),data):await addDoc(collection(db,'skills'),data);reset();await load()}catch(err){console.error(err);alert('Could not save the skill. Please try again.')}finally{button.disabled=false;if($('#id').value==='')button.textContent='Publish skill'}};$('#cancel').onclick=reset;$('#list').onclick=async e=>{let id=e.target.dataset.e||e.target.dataset.d;if(!id)return;if(e.target.dataset.d){if(confirm('Delete this skill?')){await deleteDoc(doc(db,'skills',id));await load()}return}let s=skills.find(x=>x.id===id);['name','category','icon','color','description','logoUrl'].forEach(k=>{$(`#${k}`).value=s[k]||''});showPreview(s.logoUrl);$('#id').value=id;$('#save').textContent='Save changes';$('#cancel').hidden=false;$('#note').textContent=`Editing ${s.name}.`;scrollTo({top:0,behavior:'smooth'})}}
